---
title: "MASS to valcano"
author: "Deng Zhaoguo"
format: html
self-contained: true
date: "`r Sys.Date()`"
toc: true       
toc-depth: 5    
execute:
  eval: false
  echo: TRUE
  warning: FALSE
  message: FALSE
---

# Memo

Read MASS results, merge and t.test, volcano plot

# Read files and merge, log2 transform

```{r}
# Files to merge
file_seq <- c(
  'MS211267-ACT-B10.xlsx',
  'MS211973-ACT1117.xlsx',
  'MS221737-TB.xlsx',
  'MS211267-DN2-B10.xlsx',
  'MS211973-GTRD1117.xlsx',
  'MS221737-GTRD.xlsx'
)

#Define columns: Accession (x1), Unique.peptides (x2), Abundance (x3)
x1 <- 4
x2 <- 11
x3 <- 18

# Read and merge
df_list <- lapply(file_seq, function(file) {
  read.xlsx(file, sheet = 1) %>%
    select(Accession = x1, Unique.Peptides = x2, Abundance = x3) %>%
    filter(Unique.Peptides > 2) %>%
    select(-Unique.Peptides) %>%
    mutate(Accession = sub("^(Pp\\d+c\\d+_\\d+).*", "\\1", Accession)) %>%
    rename(!!file := Abundance)
})

# log2 transform
df_merge <- reduce(df_list, full_join, by = "Accession") %>%
  replace(is.na(.), 0)

combine <- df_merge %>%
  mutate(across(-Accession, ~ log2(. + 1)))

# export
write.xlsx(combine, "raw_combine.xlsx")
```

# T test

```{r}
combine <- read.xlsx("raw_combine.xlsx")

# Set column 1 to row names
df_transform <- combine %>%
  column_to_rownames(var = colnames(combine)[1])


#Add foldchange and pval
sample <- 4:6
control <- 1:3

foldchange <- apply(df_transform, 1, function(x) mean(x[sample]) - mean(x[control]))
pval <- apply(df_transform, 1, function(x) t.test(x[sample], x[control], var.equal = TRUE)$p.value)

compare <- cbind(df_transform, foldchange, pval)
compare$qval <- p.adjust(compare$pval, method = "fdr")

# output
write.xlsx(compare, "raw_t_test.xlsx", rowNames = TRUE)
```

# Volcano plot

```{r}
data_import <- read.xlsx("raw_t_test.xlsx", sheet = 1)

data_import <- data_import %>%
  column_to_rownames(var = colnames(data_import)[1])


# Fileter
n_repeat <- 1
log2fc_cutoff <- 3
sig_cutoff <- 0.05

data_plt <- data_import[rowSums(data_import[, 4:6] > 1) >= n_repeat, ] %>%
  mutate(gene_type = case_when(
    foldchange > log2fc_cutoff & pval < sig_cutoff ~ "up",
    TRUE ~ "ns"
  ))

# image options
plot_params <- list(
  cols = c("up" = "firebrick", "down" = "#26b3ff", "ns" = "grey"),
  sizes = c("up" = 3, "down" = 3, "ns" = 2),
  alphas = c("up" = 1, "down" = 1, "ns" = 0.5)
)

p1 <- ggplot(data_plt, aes(x = foldchange, y = -log10(pval), fill = gene_type, size = gene_type, alpha = gene_type)) +
  theme_bw() +
  theme(panel.grid = element_blank()) +
  geom_point(shape = 21) +
  geom_hline(yintercept = -log10(sig_cutoff), linetype = "dashed") +
  geom_vline(xintercept = c(-log2fc_cutoff, log2fc_cutoff), linetype = "dashed") +
  scale_fill_manual(values = plot_params$cols) +
  scale_size_manual(values = plot_params$sizes) +
  scale_alpha_manual(values = plot_params$alphas)
```

## highlight *Gene Of Interest*

```{r}
# Load gene of interest (GOI)
genelist_of_interest <- read.xlsx("GOI.xlsx")

# define gene name and gene symbol
gene_name <- genelist_of_interest$gene
symbol <- genelist_of_interest$annotation


datapoints <- data_plt %>%
  rownames_to_column(var = "gene") %>%
  filter(gene %in% gene_name) %>%
  mutate(annotation = symbol[match(gene, gene_name)]) 

p2 <- p1 +
  geom_text_repel(
    data = datapoints,
    aes(x = foldchange, y = -log10(pval), label = annotation),
    size = 3,               # Label font size
    color = "black",        # Label font color
    box.padding = 0.5,      # Minimum distance between label and point
    point.padding = 0.3,    # Extra spacing between point and label
    segment.color = "grey", # Color of the connecting line
    segment.size = 0.5,     # Thickness of the connecting line
    alpha = 0.8             # Transparency of labels
  )

pdf("volcano.pdf")
plot(p2)
dev.off()
```

# output files

```{r}
data_output <- data_plt %>%
  rownames_to_column(var = "gene")  # row.names to column "gene"

# Read reference annotation
ref <- read.xlsx('PP_v6.1_synonym_anno.xlsx')

# combine and output
result <- merge(data_output,ref, by = 'gene') 
write.xlsx(result, "Result_summary.xlsx", rowNames = FALSE)
```
