---
title: "Read files"
format: html
self-contained: true
author: "Deng Zhaoguo"
date: "`r Sys.Date()`"
toc: true       # 显示目录
toc-depth: 5    # 显示三级标题
execute:
  eval: false
  echo: TRUE
  warning: FALSE
  message: FALSE
---

# Read VCF files and annotate

## 加载

```{r}

library(openxlsx)
library(dplyr)
library (tidyverse)
```

## 把样品写在list中

```{r}
samples <- c("W28", "W57", "W63", "W120", "W77", "W78")  
ref <- read.xlsx("PP_v6.1_synonym_anno.xlsx")

```

## 读取 combine.exonic_variant_function文件，并做一些处理，按突变质量QUAL排序

```{r}

for (sample in samples) {

  input_file <- paste0(sample, ".combine.exonic_variant_function")
  output_file <- paste0(sample, "_annotated.xlsx")
  

  data <- read.delim(input_file, header = FALSE)[, -1]
  colnames(data)[c(1,2,13)] <- c("Type", "Mutation", "QUAL")
  

  df <- data %>%
    mutate(Accession = sub("\\..*$", "", Mutation)) %>%
    select(Accession, everything()) %>%
    filter(Type != "synonymous SNV") %>%
    arrange(desc(QUAL))
  

  m <- left_join(df, ref, by = c("Accession" = "gene"))
  
  write.xlsx(m, output_file, rowNames = FALSE)
  
  message(sample, " done.")
}
```

# Read MASS results and merge

```{r}
file_seq <- c(
  'MS211267-ACT-B10.xlsx',
  'MS211973-ACT1117.xlsx',
  'MS221737-TB.xlsx',
  'MS211267-DN2-B10.xlsx',
  'MS211973-GTRD1117.xlsx',
  'MS221737-GTRD.xlsx'
)
```

## lapply读入函数，选取自己想要的列信息，同时进行筛选

```{r}
#确认文件 Accession (x1), Unique.peptides (x2), Abundance (x3)所在的列
x1 <- 4
x2 <- 11
x3 <- 18

# 读取并处理文件
df_list <- lapply(file_seq, function(file) {
  read.xlsx(file, sheet = 1) %>%
    select(Accession = x1, Unique.Peptides = x2, Abundance = x3) %>%
    filter(Unique.Peptides > 2) %>%
    select(-Unique.Peptides) %>%
    mutate(Accession = sub("\\..*$", "", Accession)) %>%  #Accession规范化
    rename(!!file := Abundance)      #动态重命名
})

```

## Reduce函数，log2转换

```{r}
# 合并所有文件并
df_merge <- reduce(df_list, full_join, by = "Accession") %>%
  replace(is.na(.), 0)

# 合并函数: inner_join(full_join), intersect, %in% 等等都可以使用，顺手就行

# 进行log2转化
combine <- df_merge %>%
  mutate(across(-Accession, ~ log2(. + 1)))
```

## 注释

```{r}
#annotate
ref=read.xlsx("ATH_summary_2022_SAUR_included.xlsx")
m <- left_join(combine, ref, by = c("Accession" = "gene")) #列名不同也可以合并
write.xlsx(m,"LAZY4-GFP_4_Replicates_annotated.xlsx",rowNames=F)
```
